use crate::pac::*;
use crate::syscon::periph_syscon;

periph_syscon! {
    (periph: fmu::FMU0,                     instance: 0, bit: 9, hRST: true, hCC: true)
    (periph: flexspi::FLEXSPI0,             instance: 0, bit: 11, hRST: true, hCC: true)
    (periph: inputmux::INPUTMUX0,           instance: 0, bit: 12, hRST: true, hCC: true)
    (periph: port::PORT0,                   instance: 0, bit: 13, hRST: true, hCC: true)
    (periph: port::PORT1,                   instance: 0, bit: 14, hRST: true, hCC: true)
    (periph: port::PORT2,                   instance: 0, bit: 15, hRST: true, hCC: true)
    (periph: port::PORT3,                   instance: 0, bit: 16, hRST: true, hCC: true)
    (periph: port::PORT4,                   instance: 0, bit: 17, hRST: true, hCC: true)
    (periph: gpio::GPIO0,                   instance: 0, bit: 19, hRST: true, hCC: true)
    (periph: gpio::GPIO1,                   instance: 0, bit: 20, hRST: true, hCC: true)
    (periph: gpio::GPIO2,                   instance: 0, bit: 21, hRST: true, hCC: true)
    (periph: gpio::GPIO3,                   instance: 0, bit: 22, hRST: true, hCC: true)
    (periph: gpio::GPIO4,                   instance: 0, bit: 23, hRST: true, hCC: true)
    (periph: pint::PINT0,                   instance: 0, bit: 25, hRST: true, hCC: true)
    (periph: dma::DMA0,                     instance: 0, bit: 26, hRST: true, hCC: true)
    (periph: crc::CRC0,                     instance: 0, bit: 27, hRST: true, hCC: true)
    (periph: mailbox::MAILBOX0,             instance: 0, bit: 31, hRST: true, hCC: true)

    (periph: mrt::MRT0,                     instance: 1, bit: 0, hRST: true, hCC: true)
    (periph: ostimer::OSTIMER0,             instance: 1, bit: 1, hRST: true, hCC: true)
    (periph: sct::SCT0,                     instance: 1, bit: 2, hRST: true, hCC: true)
    (periph: adc::ADC0,                     instance: 1, bit: 3, hRST: true, hCC: true)
    (periph: adc::ADC1,                     instance: 1, bit: 4, hRST: true, hCC: true)
    (periph: lpdac::DAC0,                   instance: 1, bit: 5, hRST: true, hCC: true)
    (periph: rtc::RTC0,                     instance: 1, bit: 6, hRST: true, hCC: true)
    (periph: emvsim::EMVSIM0,               instance: 1, bit: 8, hRST: true, hCC: true)
    (periph: emvsim::EMVSIM1,               instance: 1, bit: 9, hRST: true, hCC: true)
    (periph: utick::UTICK0,                 instance: 1, bit: 10, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM0,     instance: 1, bit: 11, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM1,     instance: 1, bit: 12, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM2,     instance: 1, bit: 13, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM3,     instance: 1, bit: 14, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM4,     instance: 1, bit: 15, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM5,     instance: 1, bit: 16, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM6,     instance: 1, bit: 17, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM7,     instance: 1, bit: 18, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM8,     instance: 1, bit: 19, hRST: true, hCC: true)
    (periph: lp_flexcomm::LP_FLEXCOMM9,     instance: 1, bit: 20, hRST: true, hCC: true)
    (periph: lpuart::LPUART0,               instance: 1, bit: 11, hRST: true, hCC: true)
    (periph: lpuart::LPUART1,               instance: 1, bit: 12, hRST: true, hCC: true)
    (periph: lpuart::LPUART2,               instance: 1, bit: 13, hRST: true, hCC: true)
    (periph: lpuart::LPUART3,               instance: 1, bit: 14, hRST: true, hCC: true)
    (periph: lpuart::LPUART4,               instance: 1, bit: 15, hRST: true, hCC: true)
    (periph: lpuart::LPUART5,               instance: 1, bit: 16, hRST: true, hCC: true)
    (periph: lpuart::LPUART6,               instance: 1, bit: 17, hRST: true, hCC: true)
    (periph: lpuart::LPUART7,               instance: 1, bit: 18, hRST: true, hCC: true)
    (periph: lpuart::LPUART8,               instance: 1, bit: 19, hRST: true, hCC: true)
    (periph: lpuart::LPUART9,               instance: 1, bit: 20, hRST: true, hCC: true)
    (virt: MICFIL,                          instance: 1, bit: 21, hRST: true, hCC: true)
    (periph: ctimer::CTIMER2,               instance: 1, bit: 22, hRST: true, hCC: true)
    (periph: usbdcd::USBDCD0,               instance: 1, bit: 24, hRST: true, hCC: true)
    (periph: usb::USBFS0,                   instance: 1, bit: 25, hRST: true, hCC: true)
    (periph: ctimer::CTIMER0,               instance: 1, bit: 26, hRST: true, hCC: true)
    (periph: ctimer::CTIMER1,               instance: 1, bit: 27, hRST: true, hCC: true)
    (periph: smartdma::SMARTDMA0,           instance: 1, bit: 31, hRST: true, hCC: true)

    (periph: dma::DMA1,                     instance: 2, bit: 1, hRST: true, hCC: true)
    (periph: enet::ENET0,                   instance: 2, bit: 2, hRST: true, hCC: true)
    (periph: usdhc::USDHC0,                 instance: 2, bit: 3, hRST: true, hCC: true)
    (periph: flexio::FLEXIO0,               instance: 2, bit: 4, hRST: true, hCC: true)
    (periph: i2s::SAI0,                     instance: 2, bit: 5, hRST: true, hCC: true)
    (periph: i2s::SAI1,                     instance: 2, bit: 6, hRST: true, hCC: true)
    (periph: freqme::FREQME0,               instance: 2, bit: 8, hRST: true, hCC: true)
    (periph: usbhs::USBHS1__USBC,           instance: 2, bit: 16,hRST: true, hCC: true)
    (periph: usbphy::USBPHY0,               instance: 2, bit: 17,hRST: true, hCC: true)
    (periph: powerquad::POWERQUAD0,         instance: 2, bit: 19,hRST: true, hCC: true)
    (periph: plu::PLU0,                     instance: 2, bit: 20,hRST: true, hCC: true)
    (periph: ctimer::CTIMER3,               instance: 2, bit: 21,hRST: true, hCC: true)
    (periph: ctimer::CTIMER4,               instance: 2, bit: 22,hRST: true, hCC: true)
    (periph: scg::SCG0,                     instance: 2, bit: 26,hRST: true, hCC: true)

    (periph: i3c::I3C0,                     instance: 3, bit: 0, hRST: true, hCC: true)
    (periph: i3c::I3C1,                     instance: 3, bit: 1, hRST: true, hCC: true)
    (periph: sinc::SINC0,                   instance: 3, bit: 2, hRST: true, hCC: true)
    (periph: qdc::QDC0,                     instance: 3, bit: 4, hRST: true, hCC: true)
    (periph: qdc::QDC1,                     instance: 3, bit: 5, hRST: true, hCC: true)
    (periph: pwm::PWM0,                     instance: 3, bit: 6, hRST: true, hCC: true)
    (periph: evtg::EVTG0,                   instance: 3, bit: 8, hRST: true, hCC: true)
    (periph: lpdac::DAC1,                   instance: 3, bit: 11,hRST: true, hCC: true)
    (periph: opamp::OPAMP0,                 instance: 3, bit: 13,hRST: true, hCC: true)
    (periph: opamp::OPAMP1,                 instance: 3, bit: 14,hRST: true, hCC: true)
    (periph: opamp::OPAMP2,                 instance: 3, bit: 15,hRST: true, hCC: true)
    (periph: lpcmp::CMP2,                   instance: 3, bit: 18,hRST: true, hCC: true)
    (periph: vref::VREF0,                   instance: 3, bit: 19,hRST: true, hCC: true)
    (periph: tsi::TSI0,                     instance: 3, bit: 22,hRST: true, hCC: true)
    (periph: ewm::EWM0,                     instance: 3, bit: 23,hRST: true, hCC: true)
    (periph: eim::EIM0,                     instance: 3, bit: 24,hRST: true, hCC: true)
    (periph: erm::ERM0,                     instance: 3, bit: 25,hRST: true, hCC: true)
    (periph: intm::INTM0,                   instance: 3, bit: 26,hRST: true, hCC: true)
    (periph: sema42::SEMA42_0,              instance: 3, bit: 27,hRST: true, hCC: true)
}
